.travis.yml
CMakeLists.txt
Dockerfile
SimpleTypeTests.cpp
TreeVisitor.cpp
docker-compose.yml

This adds a Dockerfile and a configuration for docker-compose to make it possible to easily test the project with different LLVM versions. For all tested LLVM versions the tests currently fail.
In addition, the cmake file is simplified to use  what is provided by the LLVM cmake config. No warnings are configured but I suggest we do that in a future PR.

Configure docker-compose to build against different LLVM versions

---

ir/Enum.cpp
ir/Enum.h
ir/IR.cpp
tests/samples/Enum.h
tests/samples/Enum.scala
tests/samples/Typedef.scala
visitor/TreeVisitor.cpp

Fix enums values

---

CMakeLists.txt
TypeTranslator.cpp
Utils.h
ir/Function.cpp
ir/Struct.cpp
scripts/test.sh
visitor/TreeConsumer.h
visitor/TreeVisitor.cpp

Constant array sizes can only be positive so remove signed conversion
of integer to Scala Native natural number encoding in favour of the
unsigned one.
Refs #39

Clean up encoding of natural numbers used in array sizes

---

ir/Enum.cpp
ir/Enum.h
ir/IR.cpp
ir/IR.h
tests/samples/Enum.h
tests/samples/Enum.scala
tests/samples/Typedef.scala
visitor/TreeVisitor.cpp

Fix underlying type of enums

---

Main.cpp
Utils.h
ir/Function.cpp
ir/Function.h
ir/IR.cpp
ir/IR.h
ir/Struct.cpp
ir/Struct.h
ir/TypeAndName.cpp
ir/TypeAndName.h
ir/TypeDef.cpp
ir/TypeDef.h
tests/samples/PrivateMembers.h
tests/samples/PrivateMembers.scala
tests/src/test/scala/org/scalanative/bindgen/BindgenSpec.scala
visitor/TreeConsumer.h

Add option `--exclude-prefix` that allows to specify prefix of declarations that should be excluded.
If chain of typedefs has aliases that should be excluded then this aliases are replaced by actual types:
```
type __int32_t = native.CInt
type __darwin_pid_t = __int32_t
type pid_t = __darwin_pid_t
``` 
=>
```
type pid_t = native.CInt
```
Also functions, structs, enums, union and typdefs are excluded if they use excluded types.
Issue #3

Filter functions and typedefs by prefix

---

ir/Function.cpp
ir/Function.h
tests/samples/Function.h
tests/samples/Function.scala

Generate new name if varArgs parameter already exist

---

visitor/TreeVisitor.cpp

Warn about packed structs

---

README.md
bindgen/TypeTranslator.cpp

Remove warnings about type qualifiers from code

---

bindgen/defines/DefineFinder.cpp

On macOS there is no ulong type.

Use unsigned long instead of ulong

---

bindgen/CMakeLists.txt
bindgen/defines/DefineFinder.cpp
bindgen/ir/Define.cpp
bindgen/ir/Define.h
bindgen/ir/IR.cpp
bindgen/ir/IR.h
bindgen/ir/PossibleVarDefine.cpp
bindgen/ir/PossibleVarDefine.h
bindgen/ir/VarDefine.cpp
bindgen/ir/VarDefine.h
bindgen/ir/Variable.cpp
bindgen/ir/Variable.h
bindgen/visitor/TreeVisitor.cpp
bindgen/visitor/TreeVisitor.h
tests/samples/LiteralDefine.h
tests/samples/VarDefine.c
tests/samples/VarDefine.h
tests/samples/VarDefine.scala
tests/samples/src/test/scala/org/scalanative/bindgen/samples/VarDefineTests.scala

During `DefineFinderAction` save all defines that use an identifier.
During AST traversal find variables declarations and check if there is a define for the variable.
If such define exist then save it in a vector field in IR and generate Scala code for it:
```c
extern int a;
#define A a
```
```scala
@name("a")
def A: native.CInt = native.extern
```

Generate bindings for defines for variables

---

.travis.yml
Dockerfile
bindgen/CMakeLists.txt
bindgen/Dockerfile
bindgen/Main.cpp
bindgen/visitor/TreeVisitor.h
docker-compose.yml

Tested on macOS with the caveat that static linked executables are not supported however all LLVM dependencies are statically linked.

Fix #33: Configure CMake to build statically linked binary

---

.travis.yml
docker-compose.yml
scripts/docker-bindgen.sh
scripts/docker-test.sh

Use the commit ID as the docker version to avoid accidental fallback
to 'latest' from docker hub.

Pin the bindgen docker image version

---

bindgen/ir/IR.cpp
bindgen/ir/VarDefine.h
bindgen/ir/Variable.cpp
bindgen/ir/Variable.h
tests/samples/Extern.c
tests/samples/Extern.h
tests/samples/Extern.scala
tests/samples/VarDefine.scala
tests/samples/src/test/scala/org/scalanative/bindgen/samples/ExternTests.scala

Due to scala-native/scala-native#202 it is not possible to use `var` so
for now `val`s are used although not semantically correct.
References #70

Generate extern variable declarations

---

bindgen/TypeTranslator.cpp
bindgen/ir/IR.cpp
bindgen/ir/Struct.cpp
bindgen/visitor/TreeVisitor.cpp
tests/samples/Struct.c
tests/samples/Struct.h
tests/samples/Struct.scala
tests/samples/Union.c
tests/samples/Union.h
tests/samples/Union.scala
tests/samples/src/test/scala/org/scalanative/bindgen/samples/StructTests.scala
tests/samples/src/test/scala/org/scalanative/bindgen/samples/UnionTests.scala

Test types that use native.CArray

---

bindgen/Utils.h
bindgen/ir/Struct.cpp
bindgen/ir/Struct.h
tests/samples/Extern.scala
tests/samples/PrivateMembers.scala
tests/samples/ReservedWords.scala
tests/samples/Struct.scala
tests/samples/src/test/scala/org/scalanative/bindgen/samples/StructTests.scala

Helper methods use pointers for fields of type CArray and CStruct

---

bindgen/Utils.h
bindgen/ir/Struct.cpp
tests/samples/ReservedWords.scala
tests/samples/Struct.c
tests/samples/Struct.h
tests/samples/Struct.scala
tests/samples/src/test/scala/org/scalanative/bindgen/samples/StructTests.scala

#93 fixed helper methods for fields of type `CStruct` and `CArray` but it did not check if type is an alias for one of these types.

Check if type is alias for struct/union before generating setter/getter

---

bindgen/TypeTranslator.cpp
bindgen/TypeTranslator.h
bindgen/Utils.h
bindgen/ir/Function.cpp
bindgen/ir/IR.cpp
bindgen/ir/IR.h
bindgen/ir/Struct.cpp
bindgen/ir/TypeAndName.cpp
bindgen/ir/TypeDef.cpp
bindgen/ir/types/ArrayType.cpp
bindgen/ir/types/ArrayType.h
bindgen/ir/types/FunctionPointerType.cpp
bindgen/ir/types/FunctionPointerType.h
bindgen/ir/types/PointerType.cpp
bindgen/ir/types/PointerType.h
bindgen/ir/types/Type.cpp
bindgen/ir/types/Type.h
bindgen/visitor/TreeVisitor.cpp
tests/samples/OpaqueTypes.h
tests/samples/OpaqueTypes.scala

Closes #78 
Closes #88
Create `TypeDef` instance that references `OpaqueType`
Replace `OpaqueType` instances by `Struct` or `Union` when types are declared

Handle opaque types

---

bindgen/ir/Struct.cpp
bindgen/ir/Struct.h
bindgen/ir/TypeAndName.cpp
bindgen/ir/TypeAndName.h
bindgen/ir/TypeDef.cpp
bindgen/ir/TypeDef.h
bindgen/ir/types/ArrayType.cpp
bindgen/ir/types/ArrayType.h
bindgen/ir/types/FunctionPointerType.cpp
bindgen/ir/types/FunctionPointerType.h
bindgen/ir/types/PointerType.cpp
bindgen/ir/types/PointerType.h
bindgen/ir/types/PrimitiveType.cpp
bindgen/ir/types/PrimitiveType.h
bindgen/ir/types/Type.cpp
bindgen/ir/types/Type.h

It used to compare pointers, I added `operator==` method to subclasses of `Type`

Proper implementation of usesType method

---

bindgen/ir/Function.cpp
bindgen/ir/Function.h
bindgen/ir/IR.cpp
bindgen/ir/IR.h
bindgen/ir/LiteralDefine.cpp
bindgen/ir/LiteralDefine.h
bindgen/ir/Struct.cpp
bindgen/ir/Struct.h
bindgen/ir/TypeAndName.cpp
bindgen/ir/TypeAndName.h
bindgen/ir/TypeDef.cpp
bindgen/ir/TypeDef.h
bindgen/ir/types/ArrayType.cpp
bindgen/ir/types/ArrayType.h
bindgen/ir/types/FunctionPointerType.cpp
bindgen/ir/types/FunctionPointerType.h
bindgen/ir/types/PointerType.cpp
bindgen/ir/types/PointerType.h
bindgen/ir/types/PrimitiveType.cpp
bindgen/ir/types/PrimitiveType.h
bindgen/ir/types/Type.cpp
bindgen/ir/types/Type.h

Fixes to #109
Fixes Function::usesType method
Do not search usages of typedef in other typedefs because result will be false positive

Do not search usages of typedef in other typedefs

---

bindgen/ir/IR.cpp
bindgen/ir/IR.h
bindgen/ir/Struct.cpp
bindgen/ir/Struct.h
bindgen/visitor/TreeVisitor.cpp

`fields` field stores shared_ptr.
Move generateGetter and generateSetter methods from Field class to Struct because the methods should not be used in Union class.

Small refactoring of StructOrUnion class

---

bindgen/Utils.h
bindgen/ir/Function.cpp
bindgen/ir/Function.h
bindgen/ir/IR.cpp
bindgen/ir/TypeDef.h
docs/src/paradox/limitations/index.md
tests/samples/Function.h
tests/samples/Function.scala
tests/samples/PrivateMembers.h
tests/samples/PrivateMembers.scala
tests/samples/ReservedWords.h
tests/samples/ReservedWords.scala

Skip functions that pass arrays or structs by value

---

bindgen/ir/IR.cpp
bindgen/ir/Struct.cpp
bindgen/ir/Struct.h
bindgen/visitor/TreeVisitor.cpp
tests/samples/Struct.c
tests/samples/Struct.h
tests/samples/Struct.scala
tests/samples/src/test/scala/org/scalanative/bindgen/samples/StructTests.scala

This approach can also be used for packed structs.
TODO:

Generate helper class for structs that have more than 22 fields

---

bindgen/ir/IR.cpp
bindgen/ir/IR.h
bindgen/ir/Struct.cpp
bindgen/ir/Struct.h
bindgen/visitor/TreeVisitor.cpp
tests/samples/Struct.h
tests/samples/Struct.scala

Because these helper methods are most likely wrong.

Do not generate helper methods for packed structs that are represented as CStruct

---

bindgen/ir/Struct.cpp
bindgen/ir/Struct.h

It does not affect output because there is only one instance of `Struct` or `Union` for any struct and union and checking pointers equality was enough. But in theory previous implementation might give false positive for unions.

Fix StructOrUnion operator==

---

bindgen/Utils.h
bindgen/defines/DefineFinder.cpp
bindgen/ir/Function.cpp
bindgen/ir/IR.cpp
bindgen/ir/IR.h
bindgen/ir/TypeDef.cpp
bindgen/ir/VarDefine.cpp
bindgen/ir/VarDefine.h
bindgen/ir/Variable.cpp
bindgen/ir/Variable.h
tests/samples/OpaqueTypes.h
tests/samples/OpaqueTypes.scala
tests/samples/include/OpaqueTypes.h
tests/src/test/scala/org/scalanative/bindgen/BindgenReportingSpec.scala

Closes #106
Replaces pointers to opaque types with pointers to `Byte`
```c
struct undefinedStruct;
struct undefinedStruct *getUndefinedStruct();
```
```scala
def getUndefinedStruct(): native.Ptr[Byte] = native.extern
```
If there exists a declaration that uses an opaque type value then the declaration is skipped and error messages are printed:
```c
struct undefinedStruct;
extern struct undefinedStruct s;
```
```
Error: type definition for struct_undefinedStruct was not found.
Error: Variable s is skipped because it references an opaque type.
```

Fix opaque types usages

---

bindgen/ir/Enum.h
bindgen/ir/Struct.h
bindgen/ir/types/ArrayType.h
bindgen/ir/types/FunctionPointerType.h
bindgen/ir/types/PointerType.h
bindgen/ir/types/Type.h

* `shared_from_this` is available in all type classes
* `StructOrUnion` inherits from `Type`

Inheritance cleanup

---

bindgen/TypeTranslator.cpp
bindgen/Utils.h
bindgen/ir/Function.cpp
bindgen/ir/Function.h
bindgen/ir/IR.cpp
bindgen/ir/IR.h
bindgen/ir/LiteralDefine.cpp
bindgen/ir/LiteralDefine.h
bindgen/ir/Struct.cpp
bindgen/ir/Struct.h
bindgen/ir/TypeAndName.cpp
bindgen/ir/TypeAndName.h
bindgen/ir/TypeDef.cpp
bindgen/ir/TypeDef.h
bindgen/ir/Variable.cpp
bindgen/ir/Variable.h
bindgen/ir/types/ArrayType.cpp
bindgen/ir/types/ArrayType.h
bindgen/ir/types/FunctionPointerType.cpp
bindgen/ir/types/FunctionPointerType.h
bindgen/ir/types/PointerType.cpp
bindgen/ir/types/PointerType.h
bindgen/ir/types/PrimitiveType.cpp

Add const qualifiers to fields of type `Type`

---

README.md
build.sbt
docs/src/paradox/obtaining-bindgen/index.md
docs/src/paradox/obtaining-bindgen/sbt-plugin.md
project/plugins.sbt
sbt-scala-native-bindgen/src/main/scala/org/scalanative/bindgen/sbt/ScalaNativeBindgenPlugin.scala
sbt-scala-native-bindgen/src/sbt-test/bindgen/generate/build.sbt
sbt-scala-native-bindgen/src/sbt-test/bindgen/generate/project/plugins.sbt
scripts/scalafmt

Configure publishing of the sbt plugin and tools library

---

bindgen/TypeTranslator.cpp
bindgen/TypeTranslator.h
bindgen/ir/IR.cpp
bindgen/ir/IR.h
bindgen/visitor/TreeVisitor.cpp
bindgen/visitor/TreeVisitor.h
tests/samples/AnonymousTypes.h
tests/samples/AnonymousTypes.scala
tests/samples/ReservedWords.h
tests/samples/ReservedWords.scala
tests/samples/Struct.scala
tests/samples/src/test/scala/org/scalanative/bindgen/samples/StructTests.scala

Generate type for anonymous structs, unions and inner enums

---

bindgen/CMakeLists.txt
bindgen/ir/Enum.cpp
bindgen/ir/Enum.h
bindgen/ir/Function.cpp
bindgen/ir/Function.h
bindgen/ir/IR.cpp
bindgen/ir/IR.h
bindgen/ir/LiteralDefine.cpp
bindgen/ir/LiteralDefine.h
bindgen/ir/LocatableType.cpp
bindgen/ir/LocatableType.h
bindgen/ir/Struct.cpp
bindgen/ir/Struct.h
bindgen/ir/TypeAndName.cpp
bindgen/ir/TypeAndName.h
bindgen/ir/TypeDef.cpp
bindgen/ir/TypeDef.h
bindgen/ir/types/ArrayType.cpp
bindgen/ir/types/ArrayType.h
bindgen/ir/types/FunctionPointerType.cpp
bindgen/ir/types/FunctionPointerType.h
bindgen/ir/types/PointerType.cpp
bindgen/ir/types/PointerType.h
bindgen/ir/types/PrimitiveType.cpp
bindgen/ir/types/PrimitiveType.h
bindgen/ir/types/Type.h

This reduces number of template functions

Implement LocatableType class

---

bindgen/ir/Struct.cpp
tests/samples/Cycles.h
tests/samples/Cycles.scala

Bindgen failed to detect such structs:
```c
struct node {
int value;
struct node *next;
};
```

Fix detection of cycles that contain one struct

---

sbt-scala-native-bindgen/src/main/scala/org/scalanative/bindgen/sbt/ScalaNativeBindgenPlugin.scala
tests/src/test/scala/org/scalanative/bindgen/BindgenReportingSpec.scala
tests/src/test/scala/org/scalanative/bindgen/BindgenSpec.scala
tools/src/main/scala/org/scalanative/bindgen/Bindgen.scala
tools/src/main/scala/org/scalanative/bindgen/Bindings.scala

Supersedes #142 (except for the `config` change).

Improve tooling and sbt-plugin error handling

---

bindgen/visitor/TreeVisitor.cpp
tests/samples/Function.scala
tests/samples/OpaqueTypes.scala
tests/samples/PrivateMembers.scala
tests/samples/ReuseBindings.scala
tests/samples/native.scala

Rename anonymous parameters to pN

---

bindgen/TypeTranslator.cpp
bindgen/TypeTranslator.h
bindgen/ir/Enum.cpp
bindgen/ir/Enum.h
bindgen/ir/IR.cpp
bindgen/ir/IR.h
bindgen/ir/TypeDef.cpp
bindgen/ir/TypeDef.h
bindgen/ir/types/PrimitiveType.cpp
bindgen/ir/types/PrimitiveType.h
bindgen/visitor/TreeVisitor.cpp
bindgen/visitor/TreeVisitor.h
tests/samples/IncludesHeader.scala
tests/samples/PrivateMembers.scala
tests/samples/Struct.scala
tests/samples/Union.scala

Generated typedefs are confusing.
The PR removes generated typedefs for enums.
If a field/parameter/variable has enum type, it references an `Enum` instance directly.
Also generated typedefs make #61 difficult to implement because enums and typedefs should be matched (in order to output enumerators right below enum type). It can be done by going through all typedefs, but it does not look good.

Do not generate TypeDef for enum

---

bindgen/ir/IR.cpp
bindgen/ir/IR.h
bindgen/ir/Struct.cpp
bindgen/ir/Union.cpp
tests/samples/AnonymousTypes.scala
tests/samples/Cycles.scala
tests/samples/Extern.scala
tests/samples/Function.scala
tests/samples/IncludesHeader.scala
tests/samples/OpaqueTypes.scala
tests/samples/PrivateMembers.scala
tests/samples/ReservedWords.scala
tests/samples/ReuseBindings.scala
tests/samples/Struct.scala
tests/samples/Union.scala
tests/samples/src/test/scala/org/scalanative/bindgen/samples/ExternTests.scala
tests/samples/src/test/scala/org/scalanative/bindgen/samples/StructTests.scala
tests/samples/src/test/scala/org/scalanative/bindgen/samples/UnionTests.scala

Move implicits to main object

---

bindgen/ir/IR.cpp
bindgen/ir/LiteralDefine.cpp
tests/samples/Cycles.scala
tests/samples/LiteralDefine.scala
tests/samples/NativeTypes.scala
tests/samples/Typedef.scala
tests/src/test/scala/org/scalanative/bindgen/BindgenReportingSpec.scala

Closes #61 
This commit also removes `@native.link("bindgentests")` `@native.extern` header for objects that do not have functions or extern variables

Move literal defines to main object

---

README.md
bindgen/ir/IR.cpp
bindgen/ir/Struct.cpp
bindgen/ir/Struct.h
build.sbt
docs/src/paradox/using-generated-bindings.md
docs/src/test/resources/vector.c
docs/src/test/resources/vector.h
docs/src/test/scala/org/example/vector.scala
docs/src/test/scala/org/scalanative/bindgen/docs/VectorSpec.scala
project/plugins.sbt
tests/samples/AnonymousTypes.scala
tests/samples/Cycles.scala
tests/samples/Extern.scala
tests/samples/Function.scala
tests/samples/IncludesHeader.scala
tests/samples/OpaqueTypes.scala
tests/samples/PrivateMembers.scala
tests/samples/ReservedWords.scala
tests/samples/ReuseBindings.scala
tests/samples/Struct.scala
tests/samples/Union.scala
tests/samples/src/test/scala/org/scalanative/bindgen/samples/StructTests.scala

Generate constructor helper

---

docs/src/paradox/bindings/iconv.md
docs/src/paradox/bindings/posix.md
docs/src/paradox/bindings/utf8proc.md
docs/src/paradox/resources/build.gradle
docs/src/paradox/resources/build.sbt
docs/src/paradox/resources/pom.xml

Show how to specify url of bintray repo to use bindings.
Instructions are still not valid because artifactId in instructions does not match real one.
For example artifactId for libiconv is `libiconv_native0.3` but docs say it's `libiconv`. I suppose we should change artifactId on bintray because it should not contain version and `_native` postfix is also strange.
@Jonas, I could not figure out how to change artifactId.
To do:

Specify resolver in bindings usage instructions

---

tests/samples/CustomNames.scala
tests/samples/ReuseBindings.h
tests/samples/ReuseBindings.json
tests/samples/ReuseBindings.scala
tests/samples/include/CustomNames.h

Test reuse of union bindings

---

bindings/iconv/src/main/scala/org/scalanative/bindings/iconv.scala
bindings/iconv/src/test/scala/org/scalanative/bindings/tests/IconvSpec.scala
bindings/posix/src/main/scala/org/scalanative/bindings/posix/fnmatch.scala
bindings/posix/src/main/scala/org/scalanative/bindings/posix/regex.scala
bindings/posix/src/test/scala/org/scalanative/bindings/tests/FnmatchSpec.scala
bindings/posix/src/test/scala/org/scalanative/bindings/tests/RegexSpec.scala
bindings/utf8proc/src/main/scala/org/scalanative/bindings/utf8proc.scala
bindings/utf8proc/src/test/scala/org/scalanative/bindings/tests/Utf8procSpec.scala
build.sbt
docs/src/paradox/bindings/iconv.md
docs/src/paradox/bindings/posix.md
docs/src/paradox/bindings/utf8proc.md
project/ParadoxSupport.scala

- Move the bindings to the org.scala-native.bindings organization.
- Move binding modules under org.scalanative.bindings dropping the
per-binding package if only one module is emitted.
- Drop the "lib" prefix from the binding artifact name.

Fix #173: Reorganize bindings
